// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
// import "./globals.css";
// import { AppSidebar } from "@/components/app-sidebar";
// import { ThemeProvider } from "next-themes";
// import { ModeToggle } from "@/components/mode-toggle";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//        <ThemeProvider
//             attribute="class"
//             defaultTheme="system"
//             enableSystem
//             disableTransitionOnChange
//         >
//           <SidebarProvider>
//             <div className="flex w-full min-h-screen ">
//               <AppSidebar />
//               <main className="flex-1 w-full">
//                 <SidebarTrigger />
//                 <ModeToggle />
//                 {children}
//               </main>
//             </div>
//           </SidebarProvider>

//         </ThemeProvider> 
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { ThemeProvider } from "next-themes";
import ConditionalLayout from "@/components/ConditionalLayout"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <ConditionalLayout>{children}</ConditionalLayout>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}





